### ISSUE TITLE
Nodes is being continuously recreated.

### ISSUE THREAD

**Issue by paradoxe35** [jedrw/kproximate#20]
Hey @jedrw,

Thanks for this beautiful project. However, while conducting my tests, I've noticed that the nodes are being recreated continuously, scaling up and down repeatedly.

I have a cluster based on K0S with three workers and one controller. After applying the deployment file below, I have six replicas, with two pending due to `Insufficient memory`. This triggers the scaler, causing it to scale up and down repeatedly.

Could you please help identify the issue? I would like to use this, in my small Proxmox setup.

Here is my Deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 8
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          resources:
            limits:
              cpu: "1"
              memory: "2048Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"
          image: nginx:1.14.2
          ports:
            - containerPort: 80
```

**Comment by jedrw** [comment]
Hi @paradoxe35 thanks for the kind words. This issue has been raised previously but I was never able to replicate it and get to the bottom of it. I just released a new version `0.2.2` last night which reverts a change to the scale down logic so please try that version and let me know if it makes any difference.

**Comment by paradoxe35** [comment]
Thanks @jedrw! 
I'm going to redo it with the new version.

**Comment by paradoxe35** [comment]
I just gave it another try, but unfortunately, it didn't work. I'm still experiencing the same behavior.
@jedrw
